CREATE TABLE users(
    id UUID PRIMARY KEY UNIQUE DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);